export let types = [
    "Chestplate",
    "Boots",
    "Helmet",
    "Leggings",
    "Sword",
    "Gem",
    "Meat",
    "Ring",
]

export let rarities = [
    "Common",
    "Uncommon",
    "Rare",
    "Epic",
    "Legendary",
]

export let itemNames = {
    "Chestplate": [
        "Iron Chestplate",
        "Steel Chestplate",
        "Mithril Chestplate",
        "Adamant Chestplate",
        "Rune Chestplate",
        "Dragon Chestplate",
        "Crystal Chestplate",
        "Obsidian Chestplate"
    ],
    "Boots": [
        "Iron Boots",
        "Steel Boots",
        "Mithril Boots",
        "Adamant Boots",
        "Rune Boots",
        "Dragon Boots",
        "Crystal Boots",
        "Obsidian Boots"
    ],
    "Helmet": [
        "Iron Helmet",
        "Steel Helmet",
        "Mithril Helmet",
        "Adamant Helmet",
        "Rune Helmet",
        "Dragon Helmet",
        "Crystal Helmet",
        "Obsidian Helmet"
    ],
    "Leggings": [
        "Iron Leggings",
        "Steel Leggings",
        "Mithril Leggings",
        "Adamant Leggings",
        "Rune Leggings",
        "Dragon Leggings",
        "Crystal Leggings",
        "Obsidian Leggings"
    ],
    "Sword": [
        "Iron Sword",
        "Steel Sword",
        "Mithril Sword",
        "Adamant Sword",
        "Rune Sword",
        "Dragon Sword",
        "Crystal Sword",
        "Obsidian Sword"
    ],
    "Gem": [
        "Ruby",
        "Sapphire",
        "Emerald",
        "Diamond",
        "Topaz",
        "Amethyst",
        "Aquamarine",
        "Jade",
        "Onyx",
        "Granite",
        "Zenyte",
        "Quartz",
        "Opal",
        "Jasper",
        "Citrine",
        "Amber",
    ],
    "Meat": [
        "Goblin Meat",
        "Shrimp Meat",
        "Shark Meat",
        "Swordfish Meat",
        "Salmon Meat",
        "Tuna Meat",
        "Lobster Meat",
        "Crab Meat",
        "Wolf Meat",
        "Bear Meat",
        "Chicken Meat",
        "Porcupine Meat",
        "Spider Meat",
        "Beetle Meat",
        "Bat Meat",
    ],
    "Ring": [
        "Ring of Magic",
        "Ring of Strength",
        "Ring of Health",
        "Ring of Defense",
        "Ring of Attack",
        "Ring of Speed",
        "Ring of Dexterity",
        "Ring of Vitality",
        "Ring of Wisdom",
    ]   
}