export let types = [
    "Helmet",
    "Chestplate",
    "Leggings",
    "Boots",
    "Sword",
    "Bow",
    "Ring",
    "Amulet",
    "Potion",
    "Gem",
    "Meat",
    "Drop"
]

export let rarities = [
    "Common",
    "Uncommon",
    "Rare",
    "Epic",
    "Legendary",
]

export let itemNames = {
    "Chestplate": [
        "Iron Chestplate",
        "Steel Chestplate",
        "Mithril Chestplate",
        "Adamant Chestplate",
        "Rune Chestplate",
        "Dragon Chestplate",
        "Crystal Chestplate",
        "Obsidian Chestplate"
    ],
    "Boots": [
        "Iron Boots",
        "Steel Boots",
        "Mithril Boots",
        "Adamant Boots",
        "Rune Boots",
        "Dragon Boots",
        "Crystal Boots",
        "Obsidian Boots"
    ],
    "Helmet": [
        "Iron Helmet",
        "Steel Helmet",
        "Mithril Helmet",
        "Adamant Helmet",
        "Rune Helmet",
        "Dragon Helmet",
        "Crystal Helmet",
        "Obsidian Helmet"
    ],
    "Leggings": [
        "Iron Leggings",
        "Steel Leggings",
        "Mithril Leggings",
        "Adamant Leggings",
        "Rune Leggings",
        "Dragon Leggings",
        "Crystal Leggings",
        "Obsidian Leggings"
    ],
    "Sword": [
        "Iron Sword",
        "Steel Sword",
        "Mithril Sword",
        "Adamant Sword",
        "Rune Sword",
        "Dragon Sword",
        "Crystal Sword",
        "Obsidian Sword"
    ],
    "Bow": [
        "Wooden Bow",
        "Iron Bow",
        "Steel Bow",
        "Mithril Bow",
        "Adamant Bow",
        "Rune Bow",
        "Dragon Bow",
        "Crystal Bow",
        "Obsidian Bow"
    ],
    "Gem": [
        "Ruby",
        "Sapphire",
        "Emerald",
        "Diamond",
        "Topaz",
        "Amethyst",
        "Aquamarine",
        "Jade",
        "Onyx",
        "Granite",
        "Zenyte",
        "Quartz",
        "Opal",
        "Jasper",
        "Citrine",
        "Amber",
    ],
    "Meat": [
        "Goblin Meat",
        "Shrimp Meat",
        "Shark Meat",
        "Swordfish Meat",
        "Salmon Meat",
        "Tuna Meat",
        "Lobster Meat",
        "Crab Meat",
        "Wolf Meat",
        "Bear Meat",
        "Chicken Meat",
        "Porcupine Meat",
        "Spider Meat",
        "Beetle Meat",
        "Bat Meat",
    ],
    "Ring": [
        "Ring of Magic",
        "Ring of Strength",
        "Ring of Health",
        "Ring of Defense",
        "Ring of Attack",
        "Ring of Speed",
        "Ring of Dexterity",
        "Ring of Vitality",
        "Ring of Wisdom",
    ],
    "Amulet": [
        "Amulet of Magic",
        "Amulet of Strength",
        "Amulet of Health",
        "Amulet of Defense",
        "Amulet of Attack",
        "Amulet of Speed",
        "Amulet of Dexterity",
        "Amulet of Vitality",
        "Amulet of Wisdom",
    ],
    "Potion": [
        "Health Potion",
        "Mana Potion",
        "Stamina Potion",
        "Strength Potion",
        "Magic Potion",
        "Defense Potion",
        "Attack Potion",
        "Speed Potion",
        "Dexterity Potion",
        "Vitality Potion",
        "Wisdom Potion",
    ],
    "Drop": [
        "Goblin Leather",
        "Shrimp Shell",
        "Shark Fin",
        "Swordfish Scale",
        "Wolf Pelt",
        "Wolf Fang",
        "Bear Fur",
        "Bear Claw",
        "Chicken Feather",
        "Chicken Egg",
        "Porcupine Fur",
        "Wyvern Scale",
        "Wyvern Fang",
        "Beetle Shell",
        "Beetle Jaw",
        "Bat Wing",
        "Spider Fang",
        "Spider Silk",
        "Bird Beak",
        "Bird Feather",
        "Bird Egg",
        "Dragon Scale",
        "Dragon Fang",
    ]
}