export let types = [
    "Helmet",
    "Chestplate",
    "Leggings",
    "Boots",
    "Sword",
    "Bow",
    "Ring",
    "Amulet",
    "Potion",
    "Gem",
    "Meat",
    "Drop"
]

export let rarities = [
    "Common",
    "Uncommon",
    "Rare",
    "Epic",
    "Legendary",
]

export let itemNames = {
    "Chestplate": [
        "Iron Chestplate",
        "Steel Chestplate",
        "Mithril Chestplate",
        "Adamant Chestplate",
        "Rune Chestplate",
        "Dragon Chestplate",
        "Crystal Chestplate",
        "Obsidian Chestplate"
    ],
    "Boots": [
        "Iron Boots",
        "Steel Boots",
        "Mithril Boots",
        "Adamant Boots",
        "Rune Boots",
        "Dragon Boots",
        "Crystal Boots",
        "Obsidian Boots"
    ],
    "Helmet": [
        "Iron Helmet",
        "Steel Helmet",
        "Mithril Helmet",
        "Adamant Helmet",
        "Rune Helmet",
        "Dragon Helmet",
        "Crystal Helmet",
        "Obsidian Helmet"
    ],
    "Leggings": [
        "Iron Leggings",
        "Steel Leggings",
        "Mithril Leggings",
        "Adamant Leggings",
        "Rune Leggings",
        "Dragon Leggings",
        "Crystal Leggings",
        "Obsidian Leggings"
    ],
    "Sword": [
        "Iron Sword",
        "Steel Sword",
        "Mithril Sword",
        "Adamant Sword",
        "Rune Sword",
        "Dragon Sword",
        "Crystal Sword",
        "Obsidian Sword"
    ],
    "Bow": [
        "Wooden Bow",
        "Iron Bow",
        "Steel Bow",
        "Mithril Bow",
        "Adamant Bow",
        "Rune Bow",
        "Dragon Bow",
        "Crystal Bow",
        "Obsidian Bow"
    ],
    "Gem": [
        "Ruby",
        "Sapphire",
        "Emerald",
        "Diamond",
        "Topaz",
        "Amethyst",
        "Aquamarine",
        "Jade",
        "Onyx",
        "Granite",
        "Zenyte",
        "Quartz",
        "Opal",
        "Jasper",
        "Citrine",
        "Amber",
    ],
    "Meat": [
        "Goblin Meat",
        "Shrimp Meat",
        "Shark Meat",
        "Swordfish Meat",
        "Salmon Meat",
        "Tuna Meat",
        "Lobster Meat",
        "Crab Meat",
        "Wolf Meat",
        "Bear Meat",
        "Chicken Meat",
        "Porcupine Meat",
        "Spider Meat",
        "Beetle Meat",
        "Bat Meat",
    ],
    "Ring": [
        "Ring of Magic",
        "Ring of Strength",
        "Ring of Health",
        "Ring of Defense",
        "Ring of Attack",
        "Ring of Speed",
        "Ring of Dexterity",
        "Ring of Vitality",
        "Ring of Wisdom",
    ],
    "Amulet": [
        "Amulet of Magic",
        "Amulet of Strength",
        "Amulet of Health",
        "Amulet of Defense",
        "Amulet of Attack",
        "Amulet of Speed",
        "Amulet of Dexterity",
        "Amulet of Vitality",
        "Amulet of Wisdom",
    ],
    "Potion": [
        "Health Potion",
        "Mana Potion",
        "Stamina Potion",
        "Strength Potion",
        "Magic Potion",
        "Defense Potion",
        "Attack Potion",
        "Speed Potion",
        "Dexterity Potion",
        "Vitality Potion",
        "Wisdom Potion",
    ],
    "Drop": [
        "Goblin Leather",
        "Shrimp Shell",
        "Shark Fin",
        "Swordfish Scale",
        "Wolf Pelt",
        "Wolf Fang",
        "Bear Fur",
        "Bear Claw",
        "Chicken Feather",
        "Chicken Egg",
        "Porcupine Fur",
        "Wyvern Scale",
        "Wyvern Fang",
        "Beetle Shell",
        "Beetle Jaw",
        "Bat Wing",
        "Spider Fang",
        "Spider Silk",
        "Bird Beak",
        "Bird Feather",
        "Bird Egg",
        "Dragon Scale",
        "Dragon Fang",
    ]
}

export let itemDescriptions = {
    // Chestplate
    "Iron Chestplate": "A basic chestplate made of iron. It is durable and has a decent amount of protection. It is also fairly cheap.",
    "Steel Chestplate": "A basic chestplate made of steel. It is very durable and has a decent amount of protection. It is also very light.",
    "Mithril Chestplate": "A basic chestplate made of mithril. It is really durable and has a good amount of protection. It is also very expensive.",
    "Adamant Chestplate": "A basic chestplate made of adamant. It is extremly durable and has a very good amount of protection. It is also very heavy.",
    "Rune Chestplate": "A basic chestplate made of a combination of runes. It is incredibly durable and has a great amount of protection against magic and physical attacks.",
    "Dragon Chestplate": "A basic chestplate made of dragon scales. It is a legendary chestplate and has a great amount of protection against magic and physical attacks.",
    "Crystal Chestplate": "A basic chestplate made of a combination of crystals. It is a mythical chestplate and has a great amount of protection against magic and physical attacks.",
    "Obsidian Chestplate": "A basic chestplate made of obsidian. It is a brittle chestplate, but it offers great magical protection. It is also very heavy.",

    // Boots
    "Iron Boots": "A basic pair of boots made of iron. They are durable and have a decent amount of protection. They are also fairly cheap.",
    "Steel Boots": "A basic pair of boots made of steel. They are very durable and have a decent amount of protection. They are also very light.",
    "Mithril Boots": "A basic pair of boots made of mithril. They are really durable and have a good amount of protection. They are also very expensive.",
    "Adamant Boots": "A basic pair of boots made of adamant. They are extremly durable and have a very good amount of protection. They are also very heavy.",
    "Rune Boots": "A basic pair of boots made of a combination of runes. They are incredibly durable and have a great amount of protection against magic and physical attacks.",
    "Dragon Boots": "A basic pair of boots made of dragon scales. They are a legendary pair of boots and have a great amount of protection against magic and physical attacks.",
    "Crystal Boots": "A basic pair of boots made of a combination of crystals. They are a mythical pair of boots and have a great amount of protection against magic and physical attacks.",
    "Obsidian Boots": "A basic pair of boots made of obsidian. They are a brittle pair of boots, but they offer great magical protection. They are also very heavy.",

    // Helmet
    "Iron Helmet": "A basic helmet made of iron. It is durable and has a decent amount of protection. It is also fairly cheap.",
    "Steel Helmet": "A basic helmet made of steel. It is very durable and has a decent amount of protection. It is also very light.",
    "Mithril Helmet": "A basic helmet made of mithril. It is really durable and has a good amount of protection. It is also very expensive.",
    "Adamant Helmet": "A basic helmet made of adamant. It is extremly durable and has a very good amount of protection. It is also very heavy.",
    "Rune Helmet": "A basic helmet made of a combination of runes. It is incredibly durable and has a great amount of protection against magic and physical attacks.",
    "Dragon Helmet": "A basic helmet made of dragon scales. It is a legendary helmet and has a great amount of protection against magic and physical attacks.",
    "Crystal Helmet": "A basic helmet made of a combination of crystals. It is a mythical helmet and has a great amount of protection against magic and physical attacks.",
    "Obsidian Helmet": "A basic helmet made of obsidian. It is a brittle helmet, but it offers great magical protection. It is also very heavy.",

    // Leggings
    "Iron Leggings": "A basic pair of leggings made of iron. They are durable and have a decent amount of protection. They are also fairly cheap.",
    "Steel Leggings": "A basic pair of leggings made of steel. They are very durable and have a decent amount of protection. They are also very light.",
    "Mithril Leggings": "A basic pair of leggings made of mithril. They are really durable and have a good amount of protection. They are also very expensive.",
    "Adamant Leggings": "A basic pair of leggings made of adamant. They are extremly durable and have a very good amount of protection. They are also very heavy.",
    "Rune Leggings": "A basic pair of leggings made of a combination of runes. They are incredibly durable and have a great amount of protection against magic and physical attacks.",
    "Dragon Leggings": "A basic pair of leggings made of dragon scales. They are a legendary pair of leggings and have a great amount of protection against magic and physical attacks.",
    "Crystal Leggings": "A basic pair of leggings made of a combination of crystals. They are a mythical pair of leggings and have a great amount of protection against magic and physical attacks.",
    "Obsidian Leggings": "A basic pair of leggings made of obsidian. They are a brittle pair of leggings, but they offer great magical protection. They are also very heavy.",

    // Sword
    "Iron Sword": "A basic sword made of iron. It is durable and it is decently sharp and fast. It is also fairly cheap.",
    "Steel Sword": "A basic sword made of steel. It is very durable and it is fairly sharp and very fast. It is also very light.",
    "Mithril Sword": "A basic sword made of mithril. It is really durable and it is really sharp and fast. It is also very expensive.",
    "Adamant Sword": "A basic sword made of adamant. It is extremly durable and it is really sharp, but slow. It is also very heavy.",
    "Rune Sword": "A basic sword made of a combination of runes. It is incredibly durable and it is really sharp and fast. It is also very powerful.",
    "Dragon Sword": "A basic sword made of dragon bones. It is a legendary sword and it is really sharp and fast. It is also very powerful.",
    "Crystal Sword": "A basic sword made of a combination of crystals. It is a mythical sword and it is really sharp and fast. It is also very powerful.",
    "Obsidian Sword": "A basic sword made of obsidian. It is a brittle sword, but it has magic dispersing properties. It is also very powerful.",

    // Bow
    "Wooden Bow": "A basic bow made of wood. It is not really durable and it is not very fast. It is also fairly cheap.",
    "Iron Bow": "A basic bow made of iron. It is durable and it is decently fast. It is also fairly cheap.",
    "Steel Bow": "A basic bow made of steel. It is very durable and it is very fast. It is also very light.",
    "Mithril Bow": "A basic bow made of mithril. It is really durable and it is really fast. It is also very expensive.",
    "Adamant Bow": "A basic bow made of adamant. It is extremly durable and it is really fast. It is also very heavy.",
    "Rune Bow": "A basic bow made of a combination of runes. It is incredibly durable and it is really fast. It is also very powerful.",
    "Dragon Bow": "A basic bow made of dragon bones. It is a legendary bow and it is really fast. It is also very powerful.",
    "Crystal Bow": "A basic bow made of a combination of crystals. It is a mythical bow and it is really fast. It is also very powerful.",
    "Obsidian Bow": "A basic bow made of obsidian. It is a brittle bow, but it has magic dispersing properties. It is also very powerful.",

    // Gem
    "Ruby": "A ruby is a red colored gem. It is very valuable and can be used to craft items.",
    "Sapphire": "A sapphire is a blue colored gem. It is very valuable and can be used to craft items.",
    "Emerald": "An emerald is a green colored gem. It is very valuable and can be used to craft items.",
    "Diamond": "A diamond is a yellow colored gem. It is very valuable and can be used to craft items.",
    "Topaz": "A topaz is a yellow colored gem. It is very valuable and can be used to craft items.",
    "Amethyst": "An amethyst is a purple colored gem. It is very valuable and can be used to craft items.",
    "Aquamarine": "An aquamarine is a blue colored gem. It is very valuable and can be used to craft items.",
    "Jade": "A jade is a green colored gem. It is very valuable and can be used to craft items.",
    "Onyx": "An onyx is a black colored gem. It is very valuable and can be used to craft items.",
    "Granite": "A granite is a black colored gem. It is very valuable and can be used to craft items.",
    "Zenyte": "A zenyte is a blue colored gem. It is very valuable and can be used to craft items.",
    "Quartz": "A quartz is a black colored gem. It is very valuable and can be used to craft items.",
    "Opal": "An opal is a blue colored gem. It is very valuable and can be used to craft items.",
    "Jasper": "A jasper is a red colored gem. It is very valuable and can be used to craft items.",
    "Citrine": "A citrine is a yellow colored gem. It is very valuable and can be used to craft items.",
    "Amber": "An amber is a yellow colored gem. It is very valuable and can be used to craft items.",

    // Meat
    "Goblin Meat": "A piece of raw meat from a goblin. It is very nutritious and can be used to craft food.",
    "Shrimp Meat": "A piece of raw meat from a shrimp. It is very nutritious and can be used to craft food.",
    "Shark Meat": "A piece of raw meat from a shark. It is very nutritious and can be used to craft food.",
    "Swordfish Meat": "A piece of raw meat from a swordfish. It is very nutritious and can be used to craft food.",
    "Salmon Meat": "A piece of raw meat from a salmon. It is very nutritious and can be used to craft food.",
    "Tuna Meat": "A piece of raw meat from a tuna. It is very nutritious and can be used to craft food.",
    "Lobster Meat": "A piece of raw meat from a lobster. It is very nutritious and can be used to craft food.",
    "Crab Meat": "A piece of raw meat from a crab. It is very nutritious and can be used to craft food.",
    "Wolf Meat": "A piece of raw meat from a wolf. It is very nutritious and can be used to craft food.",
    "Bear Meat": "A piece of raw meat from a bear. It is very nutritious and can be used to craft food.",
    "Chicken Meat": "A piece of raw meat from a chicken. It is very nutritious and can be used to craft food.",
    "Porcupine Meat": "A piece of raw meat from a porcupine. It is very nutritious and can be used to craft food.",
    "Spider Meat": "A piece of raw meat from a spider. It is very nutritious and can be used to craft food.",
    "Beetle Meat": "A piece of raw meat from a beetle. It is very nutritious and can be used to craft food.",
    "Bat Meat": "A piece of raw meat from a bat. It is very nutritious and it might poision you.",

    // Rings
    "Ring of Magic": "A ring which contains powerful magic. It is very valuable",
    "Ring of Strength": "A ring which will increase the strength of the wearer. It is very valuable",
    "Ring of Health": "A ring which will increase the health of the wearer. It is very valuable",
    "Ring of Defense": "A ring which will increase the defense of the wearer. It is very valuable",
    "Ring of Attack": "A ring which will increase the attack of the wearer. It is very valuable",
    "Ring of Speed": "A ring which will increase the speed of the wearer. It is very valuable",
    "Ring of Dexterity": "A ring which will increase the dexterity of the wearer. It is very valuable",
    "Ring of Vitality": "A ring which will increase the vitality of the wearer. It is very valuable",
    "Ring of Wisdom": "A ring which will increase the wisdom of the wearer. It is very valuable",

    // Amulets
    "Amulet of Magic": "An amulet which contains powerful magic. It is very valuable",
    "Amulet of Strength": "An amulet which will increase the strength of the wearer. It is very valuable",
    "Amulet of Health": "An amulet which will increase the health of the wearer. It is very valuable",
    "Amulet of Defense": "An amulet which will increase the defense of the wearer. It is very valuable",
    "Amulet of Attack": "An amulet which will increase the attack of the wearer. It is very valuable",
    "Amulet of Speed": "An amulet which will increase the speed of the wearer. It is very valuable",
    "Amulet of Dexterity": "An amulet which will increase the dexterity of the wearer. It is very valuable",
    "Amulet of Vitality": "An amulet which will increase the vitality of the wearer. It is very valuable",
    "Amulet of Wisdom": "An amulet which will increase the wisdom of the wearer. It is very valuable",

    // Potions
    "Health Potion": "A potion which will restore the health of whoever drinks it. It is very valuable",
    "Mana Potion": "A potion which will restore the mana of whoever drinks it. It is very valuable",
    "Stamina Potion": "A potion which will restore the stamina of whoever drinks it. It is very valuable",
    "Strength Potion": "A potion which will increase the strength of whoever drinks it. It is very valuable",
    "Magic Potion": "A potion which will increase the magic of whoever drinks it. It is very valuable",
    "Defense Potion": "A potion which will increase the defense of whoever drinks it. It is very valuable",
    "Attack Potion": "A potion which will increase the attack of whoever drinks it. It is very valuable",
    "Speed Potion": "A potion which will increase the speed of whoever drinks it. It is very valuable",
    "Dexterity Potion": "A potion which will increase the dexterity of whoever drinks it. It is very valuable",
    "Vitality Potion": "A potion which will increase the vitality of whoever drinks it. It is very valuable",
    "Wisdom Potion": "A potion which will increase the wisdom of whoever drinks it. It is very valuable",

    // Drops
    "Goblin Leather": "A piece of leather from a goblin. It is very valuable and can be used to craft items.",
    "Shrimp Shell": "A piece of shell from a shrimp. It is very valuable and can be used to craft items.",
    "Shark Fin": "A piece of fin from a shark. It is very valuable and can be used to craft items.",
    "Swordfish Scale": "A piece of scale from a swordfish. It is very valuable and can be used to craft items.",
    "Wolf Pelt": "A piece of pelt from a wolf. It is very valuable and can be used to craft items.",
    "Wolf Fang": "A piece of fang from a wolf. It is very valuable and can be used to craft items.",
    "Bear Fur": "A piece of fur from a bear. It is very valuable and can be used to craft items.",
    "Bear Claw": "A piece of claw from a bear. It is very valuable and can be used to craft items.",
    "Chicken Feather": "A piece of feather from a chicken. It is very valuable and can be used to craft items.",
    "Chicken Egg": "A piece of egg from a chicken. It is very valuable and can be used to craft items.",
    "Porcupine Fur": "A piece of fur from a porcupine. It is very valuable and can be used to craft items.",
    "Wyvern Scale": "A piece of scale from a wyvern. It is very valuable and can be used to craft items.",
    "Wyvern Fang": "A piece of fang from a wyvern. It is very valuable and can be used to craft items.",
    "Beetle Shell": "A piece of shell from a beetle. It is very valuable and can be used to craft items.",
    "Beetle Jaw": "A piece of jaw from a beetle. It is very valuable and can be used to craft items.",
    "Bat Wing": "A piece of wing from a bat. It is very valuable and can be used to craft items.",
    "Spider Fang": "A piece of fang from a spider. It is very valuable and can be used to craft items.",
    "Spider Silk": "A piece of silk from a spider. It is very valuable and can be used to craft items.",
    "Bird Beak": "A piece of beak from a bird. It is very valuable and can be used to craft items.",
    "Bird Feather": "A piece of feather from a bird. It is very valuable and can be used to craft items.",
    "Bird Egg": "A piece of egg from a bird. It is very valuable and can be used to craft items.",
    "Dragon Scale": "A piece of scale from a dragon. It is very valuable and can be used to craft items.",
    "Dragon Fang": "A piece of fang from a dragon. It is very valuable and can be used to craft items.",
}